package main.app.gui.swing.observer;

public enum MyNotification {

    NEW, SHOW, DELETE, RENAME, AUTHOR, ADD_CHILD, DELETE_CHILD,
    CANNOT_ADD_CHILD, CANNOT_DELETE_NODE, INVALID_PATH, CANNOT_RENAME, CANNOT_ADD_AUTHOR, CANNOT_EDIT_EXPLORER,
    EDIT, OVERLAP, SELECT, REPAINT, EXISTS, MOVE, NOTHING_IS_SELECTED,
    UNSUPPORTED_EXTENSION, CANNOT_SAVE, OPENED, SAVED, NO_PROJ_VIEW, WRONG_SELECTION
}
